# Generated by Django 4.1.7 on 2023-05-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_information_area_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injuries',
            options={'verbose_name': 'Injurie'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Stat'},
        ),
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('earned_run_average', models.IntegerField(blank=True, null=True)),
                ('strikeouts', models.IntegerField(blank=True, null=True)),
                ('pitches', models.IntegerField(blank=True, null=True)),
                ('strikeouts_9innings', models.IntegerField(blank=True, null=True)),
                ('strikeouts_walks', models.IntegerField(blank=True, null=True)),
                ('batting_average_allowed', models.IntegerField(blank=True, null=True)),
                ('batting_average', models.IntegerField(blank=True, null=True)),
                ('runs_batted_in', models.IntegerField(blank=True, null=True)),
                ('stolen_bases', models.IntegerField(blank=True, null=True)),
                ('runs_created', models.IntegerField(blank=True, null=True)),
                ('isolated_power', models.IntegerField(blank=True, null=True)),
                ('fielding_percentage', models.IntegerField(blank=True, null=True)),
                ('caught_stealing_percentage', models.IntegerField(blank=True, null=True)),
                ('home_runs', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcherstats', to='data.player')),
            ],
            options={
                'verbose_name': 'Pitcher Stat',
            },
        ),
    ]
