# Generated by Django 4.1.7 on 2023-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_injuries_options_alter_stats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='batting_average_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='earned_run_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='pitches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='strikeouts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='strikeouts_9innings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='strikeouts_walks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PitcherStats',
        ),
    ]
