# Generated by Django 4.1.7 on 2023-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_player_facebook_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='facebook_url',
            new_name='social_url',
        ),
    ]
